name: Audit (scheduled)

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  actions: read
  issues: write

concurrency:
  group: shared-audits-${{ github.repository }}
  cancel-in-progress: false

jobs:
  audit:
    uses: LasVegasForTransit/repository-tooling/.github/workflows/audit.yml@2cfa412166011accfb16374311dee22a61518e15
