/**
 * Starting point generated by @lvbt/repository-tooling. Replace it with the
 * package's real entry; the test beside it shows the expected shape.
 */
export function greet(name: string): string {
  return `Hello, ${name}!`;
}
